### ISSUE TITLE
Cannot decrypt file

### ISSUE THREAD

**Issue by Andrewcpu** [CodingFries/aes_crypt_null_safe#1]
Unhandled exception:
type 'Future<int?>' is not a subtype of type 'FutureOr<int>' in type cast
#0      _Cryptor._readKeys (package:aes_crypt_null_safe/src/cryptor.dart:1279:60)
<asynchronous suspension>
#1      _Cryptor.decryptFile (package:aes_crypt_null_safe/src/cryptor.dart:588:34)
<asynchronous suspension>
#2      AesCrypt.decryptFile (package:aes_crypt_null_safe/src/aescrypt.dart:356:12)
<asynchronous suspension>
#3      main (package:encrypted_client/test.dart:35:3)
<asynchronous suspension>

Process finished with exit code 255

**Comment by Andrewcpu** [comment]
Submitted PR w/ fix.. Not sure how this worked before though. https://github.com/CodingFries/aes_crypt_null_safe/pull/2

**Comment by awais-amjed** [comment]
Can you provide me with the file that produced this issue?

**Comment by Andrewcpu** [comment]
yes!
```
import 'package:aes_crypt_null_safe/aes_crypt_null_safe.dart';

main() async {
  var crypt = AesCrypt();
  crypt.setPassword('my cool password');
  crypt.setOverwriteMode(AesCryptOwMode.on);

  String filePath = "C:\\Users\\stein\\Documents\\lll.txt";
  String targetPath = "C:\\Users\\stein\\Documents\\lll.txt.aes";
  await crypt.encryptFile(filePath, targetPath);
  await crypt.decryptFile(targetPath, "./decoded_text.txt");
}
```

**Comment by awais-amjed** [comment]
I mean provide me the "111.txt" if it doesn't contain any sensitive data?

**Comment by Andrewcpu** [comment]
Ah ok! Sorry, not sensitive anymore. Just some random file.
lll.txt
```
sderc
iptables -t nat -A PREROUTING -d 167.71.187.167 -p tcp --dport 25565 -j DNAT --to 10.8.0.3
```

**Comment by awais-amjed** [comment]
Hi, I have uploaded the latest version with the fix.
I couldn't use your fix since it was force unwrapping a null value that could lead to another error.

**Comment by Andrewcpu** [comment]
That's ok! Thank you! :) 

Sorry for the bad PR.

**Comment by awais-amjed** [comment]
Nah that's totally fine. At least you highlighted the issue : )
Anyways, I'm closing this issue now.
