### ISSUE TITLE
Key and IV strings issue

### ISSUE THREAD

**Issue by harishkthedeveloper** [CodingFries/aes_crypt_null_safe#3]
I have two strings one is for KEY and one for IV but the encryption giving error of the length of the key ..

please suggest wich format we should convert the key and iv strings so that the ecryption accepts this

**Comment by awais-amjed** [comment]
Can you please share some code to reproduce it?

**Comment by harishkthedeveloper** [comment]
Tried in flutter 
`String key =
        'xxxxx-001yyy0902177zzz'; 
    String iv = 'xxxxx-aaaauqqqq0';
    
    String md5Key = generateMd5(key);
    //var keydecode = HEX.decode(md5Key + "00000000000000000000000000000000");

    String md5IV = generateMd5(iv);
    Uint8List keyuint8 =
        getUint8List(md5Key + "00000000000000000000000000000000");
    Uint8List ivuint8 = getUint8List(md5IV);

Uint8List output = encrypt(keyuint8, ivuint8, body, AesMode.cbc);

Uint8List getUint8List(md5hash) {
    List<int> list = md5hash.codeUnits;
    Uint8List bytes = Uint8List.fromList(list);
    print(bytes.length);
    //String string = String.fromCharCodes(bytes);
    return bytes;
  }
String generateMd5(String input) {
    return md5.convert(utf8.encode(input)).toString();
  }
Uint8List encrypt(Uint8List key, Uint8List iv, String srcData, AesMode mode) {
    Uint8List body = getUint8List2(srcData);

    var crypt = AesCrypt();
    //AesMode mode = AesMode.cbc;
    // Sets the encryption key and IV.
    //crypt.aesSetKeys(key, iv);
// Sets cipher mode
    //crypt.aesSetMode(mode);
    crypt.aesSetParams(key, iv, mode);

// Encrypts the data. Padding scheme - null byte (0x00).
    Uint8List encryptedData = crypt.aesEncrypt(body);
// Decrypts the data
    Uint8List decryptedData = crypt.aesDecrypt(encryptedData);

    return encryptedData;
  }

`

i have working code in node js but i am not able to achieve the same in flutter mainly the buffer thing here

`var crypto = require('crypto');
var request = require('request'); 
var fs = require('fs');

var AESCrypt = {};
String key =
        'xxxxx-001yyy0902177zzz'; 
    String iv = 'xxxxx-aaaauqqqq0';

key = crypto.createHash('md5').update(key).digest("hex");
console.log('key md5 = >', key );
key = new Buffer.from(key + "00000000000000000000000000000000", "hex");
console.log('key buffer = >', key );


iv = crypto.createHash('md5').update(iv).digest("hex");
console.log('iv md5 = >', iv );
iv = new Buffer.from(iv, "hex");
console.log('iv buffer = >', iv );

var enc = AESCrypt.encrypt(key, iv, JSON.stringify(obj_j));
var output = new Buffer.from(enc, 'hex');


AESCrypt.encrypt = function (cryptkey, iv, cleardata) {
    
    console.log('body = >', cleardata );

    var encipher = crypto.createCipheriv('aes-256-cbc', cryptkey, iv),
        encryptdata = encipher.update(cleardata, 'utf8', 'hex');

    encryptdata += encipher.final('hex');
    return encryptdata;
}
AESCrypt.decrypt = function (cryptkey, iv, encryptdata) {
    var decipher = crypto.createDecipheriv('aes-256-cbc', cryptkey, iv),
        decoded = decipher.update(encryptdata, 'hex', 'utf8');//decipher.update(encryptdata);

    decoded += decipher.final('utf8');//decipher.final();
    return decoded;
}


`

Thanks in advance if you are able to give solution for this buffer thing in flutter bcz in flutter its giving length issue and also not converting to the same format as node js
